# Generated by Django 4.2 on 2023-12-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_alter_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Void"),
                    (10, "Paid"),
                    (30, "User Canceled"),
                    (20, "Error"),
                    (31, "Refunded"),
                ],
                db_index=True,
                default=0,
                verbose_name="status",
            ),
        ),
    ]
