# Generated by Django 4.2 on 2023-10-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=500)),
                ("username", models.CharField(max_length=500)),
                ("login_date", models.DateTimeField(auto_now_add=True)),
                ("ip", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="AdminSite",
            fields=[],
            options={
                "verbose_name": "Admin",
                "verbose_name_plural": "Admin",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[],
            options={
                "verbose_name": "customer",
                "verbose_name_plural": "customers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
        ),
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("CUSTOMER", "customer"),
                    ("STAFF", "staff"),
                    ("ADMIN", "admin"),
                ],
                default="CUSTOMER",
                max_length=8,
            ),
        ),
    ]
