# Generated by Django 4.2 on 2023-11-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_loginuser_adminsite_customer_user_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LoginUser",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
