# Generated by Django 4.2 on 2023-10-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="avatar",
        ),
        migrations.AddField(
            model_name="file",
            name="file",
            field=models.FileField(
                blank=True, upload_to="files/%Y/%m/%d/", verbose_name="file"
            ),
        ),
    ]
