# Generated by Django 4.2 on 2023-10-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_remove_file_avatar_file_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to="categories/", verbose_name="avatar"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to="products/", verbose_name="avatar"
            ),
        ),
    ]
