# Generated by Django 4.2 on 2023-10-13 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_category_avatar_alter_product_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "audio"), (2, "video"), (3, "pdf")],
                default=2,
                verbose_name="file_type",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="file",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="products.product",
                verbose_name="product",
            ),
        ),
    ]
